<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\simple-tcp\SimpleTcp.csproj" />
    <ProjectReference Include="..\shared\LanChat.Shared.csproj" />
  </ItemGroup>

</Project>
